config/routes.rb
Rails.application.routes.draw do
  resources :climbers
  root "availabilities#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'dashboard', to: 'users#dashboard', as: :dashboard
  
  resources :availabilities do
    resources :comments, only: [:create, :destroy]
  end

  resources :availabilities do
    get 'on_date/:date', on: :collection, action: :on_date, as: :on_date
  end

  resources :event_requests, only: [:create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :friend_requests, only: [:index, :create, :update, :destroy]

end

app/models/climber.rb
# == Schema Information
#
# Table name: climbers
#
#  id           :bigint           not null, primary key
#  advanced     :boolean          default(FALSE)
#  beginner     :boolean          default(FALSE)
#  bio          :string           default("add bio ...")
#  boulder      :boolean          default(FALSE)
#  indoor       :boolean          default(FALSE)
#  instructor   :boolean          default(FALSE)
#  intermediate :boolean          default(FALSE)
#  lead         :boolean          default(FALSE)
#  outdoor      :boolean          default(FALSE)
#  overhang     :boolean          default(FALSE)
#  slab         :boolean          default(FALSE)
#  sport        :boolean          default(FALSE)
#  top_rope     :boolean          default(FALSE)
#  trad         :boolean          default(FALSE)
#  vertical     :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_climbers_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Climber < ApplicationRecord

  belongs_to :user

  def self.ransackable_attributes(auth_object = nil)
    ["id", "username", "bio", "instructor", "boulder", "top_rope", "lead", "vertical", "slab", "overhang", "beginner", "intermediate", "advanced", "sport", "trad", "indoor", "outdoor"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["availability", "user"]
  end

end

app/controllers/climbers_controller.rb
class ClimbersController < ApplicationController
  before_action :set_climber, only: %i[ show edit update destroy ]

  # GET /climbers or /climbers.json

  def index
    @q = Climber.includes(:user).ransack(params[:q])
    
    if params[:q]&.dig(:user_username_cont).present?
      # Fetch IDs of all users who are friends with the current user
      friend_ids = current_user.friends_ids

      # Adjust query to include the current user's profile and friends' profiles
      @climbers = @q.result
                    .where('users.id = :current_user_id OR users.is_public = :is_public OR users.id IN (:friend_ids)', 
                           { current_user_id: current_user.id, is_public: true, friend_ids: friend_ids })
                    .distinct
    else
      # In all other cases, include all climbers
      @climbers = @q.result.distinct
    end
  end


  # GET /climbers/1 or /climbers/1.json
  def show
    @climber = Climber.includes(user: :availabilities).find(params[:id])
  end

  # GET /climbers/new
  def new
    redirect_to root_path
    @climber = Climber.new
  end

  # GET /climbers/1/edit
  def edit
  end

  # POST /climbers or /climbers.json
  def create
    @climber = Climber.new(climber_params)

    respond_to do |format|
      if @climber.save
        format.html { redirect_to climber_url(@climber), notice: "Climber was successfully created." }
        format.json { render :show, status: :created, location: @climber }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @climber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climbers/1 or /climbers/1.json
  def update
    respond_to do |format|
      if @climber.update(climber_params)
        format.html { redirect_to climber_url(@climber), notice: "Climber was successfully updated." }
        format.json { render :show, status: :ok, location: @climber }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @climber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climbers/1 or /climbers/1.json
  def destroy
    redirect_to root_path
    @climber.destroy

    respond_to do |format|
      format.html { redirect_to climbers_url, notice: "Climber was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climber
      @climber = Climber.find(params[:id])
      authorize @climber
    end

    # Only allow a list of trusted parameters through.
    def climber_params
      params.require(:climber).permit(:bio, :instructor, :boulder, :top_rope, :lead, :vertical, :slab, :overhang, :beginner, :intermediate, :advanced, :sport, :trad, :indoor, :outdoor)
    end

end

app/views/climbers/_climber.html.erb
<div id="<%= dom_id climber %>" class="card-outline-0">
  <div class="card-body">
    <h5 class="card-title">
      <%= display_username(climber.user) %>

    </h5>

    <p class="card-text">
      <h6 class="card-subtitle text-muted">Bio:</h6>
      <%= climber.bio %>
    </p>

    <div class="climber-attributes">
      <% attributes = [] %>
      <% attributes << 'Instructor' if climber.instructor %>
      <% attributes << 'Boulder' if climber.boulder %>
      <% attributes << 'Top rope' if climber.top_rope %>
      <% attributes << 'Lead' if climber.lead %>
      <% attributes << 'Vertical' if climber.vertical %>
      <% attributes << 'Slab' if climber.slab %>
      <% attributes << 'Overhang' if climber.overhang %>
      <% attributes << 'Beginner' if climber.beginner %>
      <% attributes << 'Intermediate' if climber.intermediate %>
      <% attributes << 'Advanced' if climber.advanced %>
      <% attributes << 'Sport' if climber.sport %>
      <% attributes << 'Trad' if climber.trad %>
      <% attributes << 'Indoor' if climber.indoor %>
      <% attributes << 'Outdoor' if climber.outdoor %>

      <% unless attributes.empty? %>
        <h6 class="card-subtitle text-muted">Preferences:</h6>
        <p class="card-text">
          <%= attributes.join(', ') %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/climbers/_form.html.erb
<%= form_with(model: climber) do |form| %>
  <% if climber.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(climber.errors.count, "error") %> prohibited this climber from being saved:</h2>

      <ul>
        <% climber.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="col">
      <div class="card mb-3">
        <div class="card-header">Bio</div>
        <div class="card-body">

          <div class="form-group">
            <%= form.text_field :bio, class: 'form-control' %>
          </div>
        </div>
      </div>
    </div>

  <div class="row">

  

    <!-- Skill Levels -->
    <div class="col">
      <div class="card mb-3">
        <div class="card-header">Skill Level</div>
        <div class="card-body">
          <div class="form-group form-check">
            <%= form.label :beginner, style: "display: block" %>
            <%= form.check_box :beginner %>
          </div>
          <div class="form-group form-check">
            <%= form.label :intermediate, style: "display: block" %>
            <%= form.check_box :intermediate %>
          </div>
          <div class="form-group form-check">
            <%= form.label :advanced, style: "display: block" %>
            <%= form.check_box :advanced %>
          </div>
          <div class="form-group form-check">
            <%= form.label :instructor, style: "display: block" %>
            <%= form.check_box :instructor %>
          </div>
        </div>
      </div>
    </div>

    <!-- Climbing Styles -->
    <div class="col">
      <div class="card mb-3">
        <div class="card-header">Climbing Style</div>
        <div class="card-body">
          <div class="form-group form-check">
            <%= form.label :sport, style: "display: block" %>
            <%= form.check_box :sport %>
          </div>
          <div class="form-group form-check">
            <%= form.label :trad, style: "display: block" %>
            <%= form.check_box :trad %>
          </div>
          <div class="form-group form-check">
            <%= form.label :indoor, style: "display: block" %>
            <%= form.check_box :indoor %>
          </div>
          <div class="form-group form-check">
            <%= form.label :outdoor, style: "display: block" %>
            <%= form.check_box :outdoor %>
          </div>
        </div>
      </div>
    </div>
    <!-- Climbing type -->
    <div class="col">
      <div class="card mb-3">
        <div class="card-header">Climbing Type</div>
        <div class="card-body">
          <div class="form-group form-check">
            <%= form.label :boulder, style: "display: block" %>
            <%= form.check_box :boulder %>
          </div>
          <div class="form-group form-check">
            <%= form.label :top_rope, style: "display: block" %>
            <%= form.check_box :top_rope %>
          </div>
          <div class="form-group form-check">
            <%= form.label :lead, style: "display: block" %>
            <%= form.check_box :lead %>
          </div>
        </div>
      </div>
    </div>

    <!-- Angle -->
    <div class="col">
      <div class="card mb-3">
        <div class="card-header">Angle</div>
        <div class="card-body">
          <div class="form-group form-check">
            <%= form.label :vertical, style: "display: block" %>
            <%= form.check_box :vertical %>
          </div>
          <div class="form-group form-check">
            <%= form.label :slab, style: "display: block" %>
            <%= form.check_box :slab %>
          </div>
          <div class="form-group form-check">
            <%= form.label :overhang, style: "display: block" %>
            <%= form.check_box :overhang %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
<div>
    <%= form.submit "Update Climber Info", class: "btn btn-primary" %>
</div>
<% end %>

app/views/climbers/edit.html.erb
<h1>Edit <%= @climber.user.username %></h1>

<%= render "form", climber: @climber %>

<br>

<div>
  <%= link_to "Show this climber", @climber %> |
  <%= link_to "Back to climbers", climbers_path %>
</div>

app/views/climbers/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="form-group text-center mb-3">

  <h1>Climbers</h1>


</div>

<div id="filterForm">
  <%= search_form_for @q, html: { id: 'search-form' } do |f| %>

    <div class="row">

      <!-- Skill Levels -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Skill Level</div>
          <div class="card-body">
            <% ["beginner", "intermediate", "advanced"].each do |level| %>
              <div class="form-group form-check">
                <%= f.label "#{level}_eq".to_sym, level.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{level}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.check_box :instructor_eq, { class: "form-check-input" }, true, false %>
              <%= f.label :instructor_eq, "Instructor" %>
            </div>
          </div>
        </div>
      </div>

      <!-- Climbing Styles -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Climbing Style</div>
          <div class="card-body">
            <% ["sport", "trad", "indoor", "outdoor"].each do |style| %>
              <div class="form-group form-check">
                <%= f.label "#{style}_eq".to_sym, style.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{style}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Climbing type -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Climbing Type</div>
          <div class="card-body">
            <% ["boulder", "top_rope", "lead"].each do |type| %>
              <div class="form-group form-check">
                <%= f.label "#{type}_eq".to_sym, type.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{type}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Angle -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Angle</div>
          <div class="card-body">
            <% ["vertical", "slab", "overhang"].each do |angle| %>
              <div class="form-group form-check">
                <%= f.label "#{angle}_eq".to_sym, angle.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{angle}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Basic Search Fields -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Search</div>
          <div class="card-body">

            <div class="form-group"> 
              <%= f.search_field :user_username_cont, class: "form-control", placeholder: "search username ..." %>
            </div>

      
            <div class="form-group">
              <%= f.search_field :bio_cont, class: "form-control", placeholder: "search bio ..." %>
            </div>
           
          </div>

        </div>
      </div>

       <div style="text-align: center;">
        <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
          <i class="fas fa-search"></i> Search
        <% end %>

        <%= button_tag(type: 'button', class: 'btn btn-secondary', onclick: 'clearForm()') do %>
          Clear
        <% end %>

      </div>


    </div>
  <% end %>
</div>

<div id="climbers" class="container">
  <div class="row">
    <% @climbers.each do |climber| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <%= render climber %>
            <p class="card-text">
              <div class="form-group text-center mb-3">
                <%= link_to "Availability", climber, class: "btn btn-primary" %>
              </div>
            </p>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  function clearForm() {
    // Select the form using its ID
    var form = document.getElementById('search-form');

    // Reset the form
    form.reset();

    // Manually clear each input field
    form.querySelectorAll('input[type="search"]').forEach(input => input.value = '');
    form.querySelectorAll('input[type="checkbox"]').forEach(checkbox => checkbox.checked = false);

    // Redirect to the root path (Availabilities Index)
    window.location.href = '<%= climbers_path %>';
  }
</script>

app/views/climbers/new.html.erb
<h1>New climber</h1>

<%= render "form", climber: @climber %>

<br>

<div>
  <%= link_to "Back to climbers", climbers_path %>
</div>

app/views/climbers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @climber %>

<% if current_user != @climber.user && !current_user.friends_with?(@climber.user) && !current_user.already_sent_request?(@climber.user) %>
  <%= form_with url: friend_requests_path, method: :post do |form| %>
    <%= form.hidden_field :receiver_id, value: @climber.user.id %>
    <%= form.submit "Send Friend Request", class: "btn btn-primary" %>
  <% end %>
<% end %>

<% if @climber.user.is_public || current_user == @climber.user || current_user.friends_with?(@climber.user) %>


<div class="text-center mb-3">
  <h5><%= display_username(@climber.user) %>'s Availabilities</h5>
</div>


<%= month_calendar(header: {class: 'calendar-heading'}) do |date| %>
  <div class="card mb-3 calendar-cell">
    <div class="card-header">
      <%= date.strftime("%d") %>
      <%= link_to raw('<i class="fas fa-calendar-plus"></i>'), new_availability_path(start_date: date.to_date) %>

    </div>
    <div class="card-body">
      <% day_availabilities = @climber.user.availabilities.select { |a| a.start_time.to_date == date }.sort_by(&:start_time) %>
      <% day_availabilities.each do |availability| %>
        <p class="mb-1">
          <%= link_to availability.event_name, availability_path(availability), class: "text-dark" %>
          <small class="text-muted"><%= availability.start_time.strftime("%I:%M %p") %></small>
        </p>
      <% end %>
    </div>
  </div>
<% end %>

<% end %>





    <div style="padding-top: 5px;">
      <% if policy(@climber).edit? %>
        <%= link_to 'Edit', edit_climber_path(@climber), class: 'btn btn-primary' %> 
      <% end %>
   
      <%= link_to "Back to climbers", climbers_path, class: 'btn btn-secondary' %>
    </div>