config/routes.rb
Rails.application.routes.draw do
  resources :climbers
  root "availabilities#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'dashboard', to: 'users#dashboard', as: :dashboard
  
  resources :availabilities do
    resources :comments, only: [:create, :destroy]
  end

  resources :availabilities do
    get 'on_date/:date', on: :collection, action: :on_date, as: :on_date
  end

  resources :event_requests, only: [:create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :friend_requests, only: [:index, :create, :update, :destroy]

end

app/models/friend_request.rb
# == Schema Information
#
# Table name: friend_requests
#
#  id          :bigint           not null, primary key
#  status      :string           default("pending")
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  receiver_id :bigint
#  sender_id   :bigint
#
class FriendRequest < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validates :sender_id, uniqueness: { scope: :receiver_id, message: 'Friend request already sent.' }
  validate :not_self

  private

  def not_self
    errors.add(:receiver_id, "can't be equal to sender") if sender_id == receiver_id
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_friend_request, only: [:update, :destroy]

  def index
    @accepted_requests = current_user.sent_friend_requests.where(status: 'accepted') + current_user.received_friend_requests.where(status: 'accepted')
    @received_requests = current_user.received_friend_requests.where(status: 'pending')
    @sent_requests = current_user.sent_friend_requests.where(status: 'pending')
  end
  

  # POST /friend_requests
  # Creates a new friend request
  def create
    @friend_request = current_user.sent_friend_requests.new(receiver_id: params[:receiver_id])

    if @friend_request.save
      redirect_to climber_path(@friend_request.receiver.climber), notice: 'Friend request sent.'
    else
      redirect_to climbers_path, alert: 'Unable to send friend request.'
    end
  end

  # PATCH/PUT /friend_requests/1
  # Accepts a friend request
  def update
    if @friend_request.receiver == current_user
      @friend_request.update(status: 'accepted')
      redirect_to friend_requests_path, notice: 'Friend request accepted.'
    else
      redirect_to friend_requests_path, alert: 'Unable to accept this friend request.'
    end
  end

  # DELETE /friend_requests/1
  # Declines or cancels a friend request
  def destroy
    if @friend_request.receiver == current_user || @friend_request.sender == current_user
      @friend_request.destroy
      redirect_to friend_requests_path, notice: 'Friend request canceled.'
    else
      redirect_to friend_requests_path, alert: 'Unable to decline this friend request.'
    end
  end

  private

  def set_friend_request
    @friend_request = FriendRequest.find(params[:id])
  end
end

app/views/friend_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="row">
  <!-- Accepted Friend Requests -->
  <div class="col-md-4" style="margin-top: 30px;">
    <h2>Accepted Friend Requests</h2>
    <div class="list-group">
      <% @accepted_requests.each do |request| %>
        <div class="list-group-item" style="display: flex; justify-content: space-between; align-items: center;">
          <% friend = request.sender == current_user ? request.receiver : request.sender %>
          <span><%= friend.username %></span>
        </div>
      <% end %>
    </div>
  </div>

  <!-- Received Friend Requests -->
  <div class="col-md-4" style="margin-top: 30px;">
    <h2>Received Friend Requests</h2>
    <div class="list-group">
      <% @received_requests.each do |request| %>
        <div class="list-group-item" style="display: flex; justify-content: space-between; align-items: center;">
          <span><%= request.sender.username %></span>
          <div>
            <%= link_to 'Accept', friend_request_path(request), method: :patch, class: "btn btn-success" %>
            <%= link_to 'Decline', friend_request_path(request), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <!-- Sent Friend Requests -->
  <div class="col-md-4" style="margin-top: 30px;">
    <h2>Sent Friend Requests</h2>
    <div class="list-group">
      <% @sent_requests.each do |request| %>
        <div class="list-group-item" style="display: flex; justify-content: space-between; align-items: center;">
          <span><%= request.receiver.username %></span>
          <div>
            <%= link_to 'Cancel', friend_request_path(request), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-warning" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>