config/routes.rb
Rails.application.routes.draw do
  resources :climbers
  root "availabilities#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'dashboard', to: 'users#dashboard', as: :dashboard
  
  resources :availabilities do
    resources :comments, only: [:create, :destroy]
  end

  resources :availabilities do
    get 'on_date/:date', on: :collection, action: :on_date, as: :on_date
  end

  resources :event_requests, only: [:create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :friend_requests, only: [:index, :create, :update, :destroy]

end

app/models/availability.rb
# == Schema Information
#
# Table name: availabilities
#
#  id           :bigint           not null, primary key
#  advanced     :boolean          default(FALSE)
#  beginner     :boolean          default(FALSE)
#  boulder      :boolean          default(FALSE)
#  description  :string
#  end_time     :datetime
#  event_name   :string
#  indoor       :boolean          default(FALSE)
#  intermediate :boolean          default(FALSE)
#  lead         :boolean          default(FALSE)
#  learn        :boolean          default(FALSE)
#  location     :string
#  outdoor      :boolean          default(FALSE)
#  overhang     :boolean          default(FALSE)
#  slab         :boolean          default(FALSE)
#  sport        :boolean          default(FALSE)
#  start_time   :datetime
#  top_rope     :boolean          default(FALSE)
#  trad         :boolean          default(FALSE)
#  vertical     :boolean          default(FALSE)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_availabilities_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Availability < ApplicationRecord
  belongs_to :user # The host of the event
  has_many :event_requests, dependent: :destroy
  has_many :comments, dependent: :destroy

  #has_many :guests, through: :event_requests, source: :user

  validates :event_name, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_after_start_time

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "end_time", "event_name", "id", "start_time", "updated_at", "user_id", "advanced", "beginner", "boulder", "indoor", "instructor", "intermediate", "lead", "outdoor", "overhang", "slab", "sport", "top_rope", "trad", "vertical", "learn", "location"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["comments", "event_requests", "user"]
  end


  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?

    if end_time < start_time
      errors.add(:end_time, "must be after the start time")
    end
  end

end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: %i[ show edit update destroy ]

  # app/controllers/availabilities_controller.rb


  # app/controllers/availabilities_controller.rb
  def on_date
    @date = Date.parse(params[:date])
    @availabilities_on_date = Availability.includes(user: :climber)
                                          .where('DATE(start_time) = ?', @date)
                                          .order(start_time: :asc)
  end

  # GET /availabilities or /availabilities.json

  def index
    @q = Availability.ransack(params[:q])
    @availabilities = @q.result.includes(:user, event_requests: :user)
                        .distinct
  end

  # GET /availabilities/1 or /availabilities/1.json
  def show
    @availability = Availability.find(params[:id])
    @event_requests = @availability.event_requests.includes(:user)
    @comments = @availability.comments.order(created_at: :desc)
  end
  

  # GET /availabilities/new
  def new
    @availability = Availability.new
    @availability.start_time = params[:start_date] if params[:start_date].present?
  end

  # GET /availabilities/1/edit
  def edit
    @availability = Availability.find(params[:id])
    authorize @availability
  rescue Pundit::NotAuthorizedError
    redirect_to root_path
  end
  

  # POST /availabilities or /availabilities.json
  def create
    @availability = current_user.availabilities.new(availability_params)
    authorize @availability

    respond_to do |format|
      if @availability.save
        format.html { redirect_to availability_url(@availability), notice: "Availability was successfully created." }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1 or /availabilities/1.json
  def update
    authorize @availability
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to availability_url(@availability), notice: "Availability was successfully updated." }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1 or /availabilities/1.json
  def destroy
    authorize @availability

    @availability.destroy

    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: "Availability was successfully destroyed." }
      format.json { head :no_content }
    end

  end

  private
  
  def set_availability
    @availability = Availability.find(params[:id])
    authorize @availability unless action_name == 'show'
  end
  

  def availability_params
    params.require(:availability).permit(:event_name, :start_time, :end_time, :user_id, :advanced, :beginner, :boulder, :indoor, :instructor, :intermediate, :lead, :outdoor, :overhang, :slab, :sport, :top_rope, :trad, :vertical, :learn, :location, :description)
  end
    
end

app/views/availabilities/_availability.html.erb
<div id="<%= dom_id availability %>">
  <p>
    <strong style="font-size: larger;"><%= availability.event_name %></strong>
  </p>

  <p>
    With 
    <strong>
      <%= link_to display_username(availability.user), climber_path(availability.user.climber) if availability.user.climber %>
    </strong>
  </p>




  <p>
    <i class="fas fa-play-circle"></i>
    <span class="avail-date"><%= availability.start_time.strftime("%b %d, %Y") %></span>
    <span class="avail-time"><%= availability.start_time.strftime("%I:%M %p") %></span>
  </p>

  <p>
    <i class="fas fa-stop-circle"></i>
    <span class="avail-date"><%= availability.end_time.strftime("%b %d, %Y") %></span>
    <span class="avail-time"><%= availability.end_time.strftime("%I:%M %p") %></span>
  </p>
  <p>
    <!-- Display Location -->
    <% if availability.location.present? %>
      <strong>
        <p>@ <%= availability.location %></p>
      </strong>
    <% end %>
  </p>
  <ul>
    <% [ :advanced, :beginner, :boulder, :indoor, :intermediate, :lead, :outdoor, :overhang, :slab, :sport, :top_rope, :trad, :vertical, :learn ].each do |attribute| %>
      <% if availability.send(attribute) %>
        <li><%= attribute.to_s.humanize %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/availabilities/_event_request.html.erb
<li class="list-group-item" id="event_request_<%= event_request.id %>">
  <%= event_request.user.username %>
</li>

app/views/availabilities/_form.html.erb
<div class="container">
  <%= form_with(model: availability, class: 'needs-validation', novalidate: true) do |form| %>
    <% if availability.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading"><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h4>
        <ul>
          <% availability.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= form.label :event_name %>
          <%= form.text_field :event_name, class: 'form-control' %>
        </div>

        <div class="field">
          <%= form.label :description %>
          <%= form.text_field :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :start_time %>
          <%= form.datetime_field :start_time, value: availability.start_time&.strftime("%Y-%m-%dT%H:%M"), class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :end_time %>
          <%= form.datetime_field :end_time, value: availability.start_time&.strftime("%Y-%m-%dT%H:%M"), class: 'form-control' %>
        </div>

        <div class="row">
          <!-- Skill Levels -->
          <div class="col">
            <div class="card mb-3">
              <div class="card-header">Skill Level</div>
              <div class="card-body">
                <div>
                  <%= form.check_box :beginner, class: 'form-check-input' %>
                  <%= form.label :beginner, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :intermediate, class: 'form-check-input' %>
                  <%= form.label :intermediate, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :advanced, class: 'form-check-input' %>
                  <%= form.label :advanced, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :learn, class: 'form-check-input' %>
                  <%= form.label :learn, 'Learning', class: 'form-check-label' %>
                </div>
              </div>
            </div>
          </div>

          <!-- Climbing Styles -->
          <div class="col">
            <div class="card mb-3">
              <div class="card-header">Climbing Style</div>
              <div class="card-body">
                <div>
                  <%= form.check_box :indoor, class: 'form-check-input' %>
                  <%= form.label :indoor, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :outdoor, class: 'form-check-input' %>
                  <%= form.label :outdoor, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :sport, class: 'form-check-input' %>
                  <%= form.label :sport, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :trad, class: 'form-check-input' %>
                  <%= form.label :trad, class: 'form-check-label' %>
                </div>
              </div>
            </div>
          </div>

          <!-- Climbing Type -->
          <div class="col">
            <div class="card mb-3">
              <div class="card-header">Climbing Type</div>
              <div class="card-body">
                <div>
                  <%= form.check_box :boulder, class: 'form-check-input' %>
                  <%= form.label :boulder, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :top_rope, class: 'form-check-input' %>
                  <%= form.label :top_rope, 'Top Rope', class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :lead, class: 'form-check-input' %>
                  <%= form.label :lead, class: 'form-check-label' %>
                </div>
              </div>
            </div>
          </div>

          <!-- Angle -->
          <div class="col">
            <div class="card mb-3">
              <div class="card-header">Angle</div>
              <div class="card-body">
                <div>
                  <%= form.check_box :vertical, class: 'form-check-input' %>
                  <%= form.label :vertical, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :slab, class: 'form-check-input' %>
                  <%= form.label :slab, class: 'form-check-label' %>
                </div>
                <div>
                  <%= form.check_box :overhang, class: 'form-check-input' %>
                  <%= form.label :overhang, class: 'form-check-label' %>
                </div>
              </div>
            </div>
          </div>

          <!-- Location Field -->
          <div class="col">
            <div class="card mb-3">
              <div class="card-header">Location</div>
              <div class="card-body">
                <div class="form-group">
                  <%= form.text_field :location, class: 'form-control' %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
            <i class="fas fa-plus"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/availabilities/edit.html.erb
<h1>Editing availability</h1>

<%= render "form", availability: @availability %>

<br>

<div>
  <%= link_to "Show this availability", @availability %> |
  <%= link_to "Back to availabilities", availabilities_path %>
</div>

app/views/availabilities/index.html.erb
<p style="color: green"><%= notice %></p>

<div style="text-align: center;">

  <h1>Climb Times</h1>
  <%= link_to new_availability_path(start_date: Date.today), class: "btn btn-primary your-custom-class" do %>
    <i class="fas fa-calendar-plus fa-2x" style="vertical-align: middle;"></i>
    <span style="vertical-align: middle;">New Availability</span>
  <% end %>
</div>

<!-- class="mt-5" is prob better. Inline styles are a no-no -->
<div style="margin-top: 10px;">
  <%= search_form_for @q, html: { id: 'search-form' } do |f| %>

    <div class="row">

      <!-- Basic Search Fields -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Search</div>
          <div class="card-body">

            <div class="form-group">

              <div class="form-group">
                <%= f.label :location_cont, "Location " %>
                <%= f.search_field :location_cont, class: 'form-control', placeholder: 'Enter location...' %>
              </div>
              <div class="col">
                <%= f.label :event_name_cont, "Event" %>
                <%= f.search_field :event_name_cont, class: "form-control", placeholder: "Search Event" %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Skill Levels -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Skill Level</div>
          <div class="card-body">
            <% ["beginner", "intermediate", "advanced"].each do |level| %>
              <div class="form-group form-check">
                <%= f.label "#{level}_eq".to_sym, level.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{level}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.check_box :learn_eq, { class: "form-check-input" }, true, false %>
              <%= f.label :learn_eq, "Learn" %>
            </div>
          </div>
        </div>
      </div>

      <!-- Climbing Styles -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Climbing Style</div>
          <div class="card-body">
            <% ["sport", "trad", "indoor", "outdoor"].each do |style| %>
              <div class="form-group form-check">
                <%= f.label "#{style}_eq".to_sym, style.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{style}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Climbing type -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Climbing Type</div>
          <div class="card-body">
            <% ["boulder", "top_rope", "lead"].each do |type| %>
              <div class="form-group form-check">
                <%= f.label "#{type}_eq".to_sym, type.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{type}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <!-- Angle -->
      <div class="col">
        <div class="card mb-3">
          <div class="card-header">Angle</div>
          <div class="card-body">
            <% ["vertical", "slab", "overhang"].each do |angle| %>
              <div class="form-group form-check">
                <%= f.label "#{angle}_eq".to_sym, angle.capitalize, class: "form-check-label" %>
                <%= f.check_box "#{angle}_eq".to_sym, { class: "form-check-input" }, true, false %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>

    <div style="text-align: center;">
      <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
        <i class="fas fa-search"></i> Search
      <% end %>

      <%= button_tag(type: 'button', class: 'btn btn-secondary', onclick: 'clearForm()') do %>
        Clear
      <% end %>

    </div>

  <% end %>

</div>

<%= month_calendar(header: {class: 'calendar-heading'}) do |date| %>
  <div class="card mb-3 calendar-cell">
    <div class="card-header">
      <%= date.strftime("%d") %>
      <%= link_to raw('<i class="fas fa-calendar-plus"></i>'), new_availability_path(start_date: date.to_date) %>

    </div>
    <div class="card-body">
      <% day_availabilities = @availabilities.select { |a| a.start_time.to_date == date }.sort_by(&:start_time) %>
      <% day_availabilities.take(3).each do |availability| %>
        <p class="mb-1">
          <%= link_to availability.event_name, availability_path(availability), class: "text-dark" %>
          <small class="text-muted"><%= availability.start_time.strftime("%I:%M %p") %></small>
        </p>
      <% end %>
      <% if day_availabilities.count > 3 %>

        <%= link_to "View all #{day_availabilities.count} availabilities", on_date_availabilities_path(date.to_date) %>

      <% end %>
    </div>
  </div>
<% end %>

<script>
  function clearForm() {
    // Select the form using its ID
    var form = document.getElementById('search-form');

    // Reset the form
    form.reset();

    // Manually clear each input field
    form.querySelectorAll('input[type="search"]').forEach(input => input.value = '');
    form.querySelectorAll('input[type="checkbox"]').forEach(checkbox => checkbox.checked = false);

    // Redirect to the root path (Availabilities Index)
    window.location.href = '<%= availabilities_path %>';
  }
</script>

app/views/availabilities/new.html.erb
<div class="container">

<h1>New availability</h1>

<%= render "form", availability: @availability %>

</div>

app/views/availabilities/on_date.html.erb
<div style="text-align: center;">
<h1><%= @date.strftime("%B %d, %Y") %></h1>
</div>
<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Event Name</th>
      <th>Host</th>
    </tr>
  </thead>
  <tbody>
    <% @availabilities_on_date.each do |availability| %>
      <tr>
        <td><%= availability.start_time.strftime("%H:%M") %></td>
        <td><%= availability.end_time.strftime("%H:%M") %></td>
        <td><%= link_to availability.event_name, availability_path(availability) %></td>
        <td>
          <% if availability.user.present? %>
            <%= link_to display_username(availability.user), climber_path(availability.user.climber) if availability.user.climber %>
            <% else %>
              No User Profile
            <% end %>
        </td>

      </tr>
    <% end %>
    <% if @availabilities_on_date.empty? %>
      <tr>
        <td colspan="4">No availabilities for this date.</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/availabilities/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mt-3">

  <div class="row">
    <div class="col-md-8">

      <div class="container">

        <%= render @availability %>

        <div class="row">

          <!-- Accepted Guests -->
          <div class="col" style="padding-bottom: 10px;">

            <% if current_user && @availability.user != current_user %>
              <% unless @availability.event_requests.exists?(user: current_user) %>
                <%= form_for(current_user.event_requests.new, url: event_requests_path, remote: true, class: 'd-flex justify-content-end') do |f| %>
                  <%= f.hidden_field :availability_id, value: @availability.id %>
                  <%= button_tag(type: "submit", class: "btn btn-primary", id: "join-event-button") do %>
                    <i class="fas fa-user-plus"></i>Request to Join
                  <% end %>
                <% end %>
              <% end %>
            <% end %>

            <% if current_user %>
              <% current_user_event_request = @event_requests.find { |er| er.user_id == current_user.id } %>
              <% if current_user_event_request && current_user_event_request.status == 'pending' %>
                <button type="button" class="btn btn-secondary" disabled>Pending</button>

              <% end %>
            <% end %>
            <div class="row">
              <h4 id="accepted_header"> Participants(<%= @event_requests.count { |er| er.status == 'accepted' } %>)</h4>
            </div>

            <ul class="list-group" id="accepted_guests_list">
              <% @event_requests.select { |er| er.status == 'accepted' }.each do |event_request| %>
                <li class="list-group-item" id="event_request_<%= event_request.id %>">
                  <%= link_to event_request.user.username, climber_path(event_request.user.climber) if event_request.user.climber %>
                </li>
              <% end %>
            </ul>

          </div>

          <!-- Pending Guests -->
          <% if current_user == @availability.user %>
            <div class="col" style="padding-bottom: 10px;">
              <% pending_requests = @event_requests.select { |er| er.status == 'pending' } %>

              <h4>Pending</h4>
              <div class="card">
                <div class="card-body">
                  <table class="table">

                    <tbody>
                      <% pending_requests.each do |event_request| %>
                        <tr id="event_request_<%= event_request.id %>">
                          <td>
                            <%= link_to event_request.user.username, climber_path(event_request.user.climber) if event_request.user.climber %>
                          </td>
                          <td>
                            <div class="d-flex">
                              <%= button_to 'Reject', reject_event_request_path(event_request), method: :post, remote: true, class: 'btn btn-danger btn-sm me-2', data: { turbo: false } %>
                              <%= button_to 'Accept', accept_event_request_path(event_request), method: :post, remote: true, class: 'btn btn-success btn-sm', data: { turbo: false } %>
                            </div>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          <% end %>

          <!-- Rejected Guests -->
          <% if current_user == @availability.user %>
            <div class="col" style="padding-bottom: 10px;">

              <h4 id="rejected_guests_header">Rejected </h4>

              <ul class="list-group" id="rejected_guests_list">
                <% @event_requests.select { |er| er.status == 'rejected' }.each do |event_request| %>
                  <li class="list-group-item" id="event_request_<%= event_request.id %>">
                    <%= link_to event_request.user.username, climber_path(event_request.user.climber) if event_request.user.climber %>
                  </li>
                <% end %>
              </ul>

            </div>

          </div>

        </div>

      <% end %>

    </div>
    <div class="col-md-8">
      <div style="padding-top: 15px;">
        <h4>Description</h4>
        <div class="card mb-3">
          <div class="card-body">
            <%= @availability.description %>
          </div>
        </div>
      </div>

      <h4>Comments</h4>
      <div class="card mb-3">
        <div class="card-body">
          <% @comments.each do |comment| %>

            <div class="d-flex justify-content-between">
              <p><strong><%= comment.user.username %>:</strong> <%= comment.body %></p>
              <% if current_user == comment.user %>
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton<%= comment.id %>" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-ellipsis-v"></i>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton<%= comment.id %>">
                    <li>
                      <%= button_to 'Delete', 
                                availability_comment_path(@availability, comment),
                                method: :delete,
                                data: { confirm: 'Are you sure?' },
                                class: 'dropdown-item' %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </div>

          <% end %>
        </div>
      </div>

      <%= form_for([@availability, @availability.comments.new], html: { class: "mb-3" }) do |f| %>
        <div class="form-group">
          <%= f.text_area :body, class: "form-control", rows: 3 %>
        </div>

        <div class="form-group d-flex justify-content-end">
          <%= f.button 'Comment<i class="fas fa-paper-plane"></i>'.html_safe, type: :submit, class: "btn btn-primary" %>
        </div>

      <% end %>
    </div>
  </div>

  <% if policy(@availability).update? && policy(@availability).destroy? %>
    <div class="col-md-4">
      <div class="dropdown">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-cog"></i>
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><%= link_to "Edit this availability", edit_availability_path(@availability), class: 'dropdown-item' %></li>
          <li><%= button_to "Destroy this availability", @availability, method: :delete, class: 'dropdown-item', data: { confirm: 'Are you sure?' } %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>