config/routes.rb
Rails.application.routes.draw do
  resources :climbers
  root "availabilities#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'dashboard', to: 'users#dashboard', as: :dashboard
  
  resources :availabilities do
    resources :comments, only: [:create, :destroy]
  end

  resources :availabilities do
    get 'on_date/:date', on: :collection, action: :on_date, as: :on_date
  end

  resources :event_requests, only: [:create] do
    member do
      post :accept
      post :reject
    end
  end

  resources :friend_requests, only: [:index, :create, :update, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Belay Board</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">



    <div class="container-fluid">



    
      <%= link_to "Belay Board", root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          

          <%= link_to 'Dashboard', dashboard_path, class: "nav-link" %>
          <%= link_to "Climbers", climbers_path, class: "nav-link" %>
          <%= link_to "Friend Requests", friend_requests_path, class: "nav-link" %>
          
          
          
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">                
                <%= link_to 'Edit My Climber Info', edit_climber_path(current_user.climber.id), class: "dropdown-item" %>
                <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </ul>
            </li>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">

    <%= yield %>

</div>
  </body>
</html>